"""Add zone column to Room

Revision ID: 8fe4670d515a
Revises: 6af3f7c5f5b7
Create Date: 2025-10-30 12:35:47.164123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fe4670d515a'
down_revision = '6af3f7c5f5b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('zone', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.drop_column('zone')

    # ### end Alembic commands ###
