"""Allow null room_id in inspection_tasks

Revision ID: b9adf860c981
Revises: db2b8525cfcf
Create Date: 2025-10-30 21:36:02.928220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9adf860c981'
down_revision = 'db2b8525cfcf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inspection_tasks', schema=None) as batch_op:
        batch_op.alter_column('room_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key(None, 'rooms', ['room_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inspection_tasks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('room_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
