"""add inspection_tasks table

Revision ID: db2b8525cfcf
Revises: 8fe4670d515a
Create Date: 2025-10-30 20:53:33.803979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db2b8525cfcf'
down_revision = '8fe4670d515a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inspection_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('done_on_behalf_user_id', sa.Integer(), nullable=True),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('zone_name', sa.String(length=100), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('location_name', sa.String(length=255), nullable=True),
    sa.Column('area_scores', sa.JSON(), nullable=True),
    sa.Column('zone_score', sa.Float(), nullable=True),
    sa.Column('facility_score', sa.Float(), nullable=True),
    sa.Column('submission_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inspection_tasks')
    # ### end Alembic commands ###
